
### Get admin stats
GET http://localhost:3000/api/stats
Content-Type: application/json

### Get all communities
GET http://localhost:3000/api/communities 
Content-Type: application/json

### Get all platform transactions
GET http://localhost:3000/api/transactions
Content-Type: application/json

### Get all users
GET http://localhost:3000/api/users
Content-Type: application/json

### Delete single user
DELETE http://localhost:3000/api/remove-user/u10
Content-Type: application/json

### change community status
PUT http://localhost:3000/api/change-community-status/c3
Content-Type: application/json

{
  "status": "private"
}

### Other APIs for examples

### Create new user
PUT http://localhost:3000/api/create-user
Content-Type: application/json

{
  "id": "u10",
  "name": "New User",
  "email": "email@example.com",
  "role": "member",
  "joinedAt": "2024-06-15T10:00:00Z"
}

### Delete community
DELETE http://localhost:3000/api/remove-community/
Content-Type: application/json

### Delete transaction
DELETE http://localhost:3000/api/remove-transaction/
Content-Type: application/json